swagger: '2.0'
info:
  version: 1.0.0
  title: Microservice for Chat
  description: Js + FireStore
  license:
    name: Software Architecture, 2019-II
host: localhost:4002
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /messages:
    post:
      summary: Creates a new message
      operationId: createMessage
      parameters:
        - name: message
          in: body
          required: true
          description: Message Object
          schema:
            $ref: '#/definitions/Message'
      responses:
        '201':
          description: Send
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/ErrorModel'
        '500':
          description: Internal Server Error
          schema:
            $ref: '#/definitions/ErrorModel'

definitions:

  # Messages
  Message:
    type: object
    properties:
      message:
        type: object
        required:
          - sent
          - received
          - content
        properties:
          sent:
            type: string
          received:
            type: string
          content:
            type: string

  # Errors
  ErrorModel:
    type: object
    required:
      - data
    properties:
      data:
        type: object
        properties:
          errors: 
           type: string
